Viv/feature/29
Invivoo/ViV-Wallet pull request #72
Opened 2020-09-09 12:23 UTC by wael-mkaddem

UI : En tant que membre de l'équipe Admin, je veux pouvoir indiquer qu'une partie des VIV va être transformée en paie à une date précise #29

2020-09-09 15:51 UTC, nicolaserny commented
Est ce que tu peux rajouter un screenshot et/ou vidéo Loom ? ça facilitera la review de la partie UI.
Il y a aussi les builds qui ne passent pas (sûrement pas bien méchant)
J'essaierai de regarder la PR rapidement.

2020-09-10 14:44 UTC, wael-mkaddem commented
il suffit d'appeler l'écran avec payment/userId 

![id1](https://user-images.githubusercontent.com/68220713/92747395-71480780-f384-11ea-81b6-5bb501e7a7b6.PNG)

Quand il y a pas d'actions à payer pour un user ( hot edit pour l'id 2 )

![nopaid actions](https://user-images.githubusercontent.com/68220713/92747616-a94f4a80-f384-11ea-9bb5-13b4e45abba5.PNG)

Quand l'id est erroné 

![idnotfound](https://user-images.githubusercontent.com/68220713/92747685-bec47480-f384-11ea-86d7-14c9b6573777.PNG)

2020-09-11 12:00 UTC, nicolaserny requested changes

2020-09-11 12:02 UTC, nicolaserny commented
@Brounchy est-ce que tu pourras faire une review de la partie java ?

2020-09-11 13:59 UTC, wael-mkaddem commented
Merci pour la review , je m'occupe de faire le nécessaire. Pour le code java, ce sont pas mes changements, je crois que c'est dû au rebase

2020-09-15 10:14 UTC, wael-mkaddem commented on viv-wallet-app/src/views/Payment.vue
> +            <div v-if="loading">Loading...</div>
Done

2020-09-15 10:14 UTC, wael-mkaddem commented on viv-wallet-app/src/services/wallet.ts
> +        const rawData = (await this.http.get(`${userId}/actions`)).data;
Done

2020-09-15 10:14 UTC, wael-mkaddem commented on viv-wallet-app/src/views/Payment.vue
> +            <h2>Payment</h2>
done

2020-09-15 10:14 UTC, wael-mkaddem commented on viv-wallet-app/src/views/Payment.vue
> +                    <label id="input-date-1" label-for="lbl-date-1">DATE</label>
done

2020-09-15 10:14 UTC, wael-mkaddem commented on viv-wallet-app/src/views/Payment.vue
> +                    <label id="lbl-viv-1" label-for="p-viv-1">TOTAL VIVs</label>
done

2020-09-15 10:14 UTC, wael-mkaddem commented on viv-wallet-app/src/views/Payment.vue
> +            this.user = await this.usersService.getUser(this.id);
Done

2020-09-15 10:15 UTC, wael-mkaddem commented
@nicolaserny  Dis moi si c'est ok pour toi

2020-09-15 10:17 UTC, wael-mkaddem commented on viv-wallet-app/src/views/Payment.vue
> +                    fullName="Théophile Montgommery"
Done

2020-09-16 12:19 UTC, nicolaserny commented
@wael-mkaddem j'ai une question. tu es sûr que tu as fait un merge ou un rebase car normalement je ne devrais pas le code de nos commits dans la review (qui est un diff). On dirait que tu as des cherry picks des commits...

2020-09-16 15:14 UTC, wael-mkaddem commented
J'avais fait des rebase pas mal de fois sur la branche. Sinon pour être sûr à 100 % je peux faire des cherrypick des mes commits et forcer un push. On va peut-être perdre le review.

2020-09-16 15:26 UTC, nicolaserny commented
@wael-mkaddem  c'est très bizarre car l'historique n'est pas cohérent avec un rebase. c'est pour ça que je posais la question.

2020-09-17 13:54 UTC, nicolaserny approved these changes

2020-09-17 13:55 UTC, nicolaserny commented
@wael-mkaddem j'ai mis à jour ta branche par rapport à develop. Je valide et merge ta PR. merci :)

2020-09-17 13:55 UTC, merged